apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-weather-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app
        image: webage.azurecr.io/weather-app:v1
        ports:
        - containerPort: 5070
---
apiVersion: v1
kind: Service
metadata:
  name: service-weather-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5070
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: weather-app
