apiVersion: v1
kind: Service
metadata:
  labels:
    app: restaurant-web
  name: restaurant-web-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    app: restaurant-web
  type: LoadBalancer