apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: busybox-wait
        image: busybox
        command: ["sh", "-c", "sleep 60"]
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80