apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: cr.bah.com/nginx
        name: nginx
        ports:
        - containerPort: 81
      imagePullSecrets:
      - name: regcred
status: {}

# kubectl create deployment nginx --image=nginx --port=80
