apiVersion: v1
kind: Service
metadata:
  labels:
    app: restaurant-api
  name: restaurant-api-service
spec:
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: restaurant-api
  type: ClusterIP